spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

server:
  port: 0

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgresql-instance-1.cfce96mjt0tp.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
  rabbitmq:
    host: 172.31.41.173
    username: guest
    password: guest
    port: 5672
server:
  port: 8081
